
server:
  port: 8085

spring:
  application:
    name: patient-management-service

  datasource:
    url: jdbc:postgresql://db:5432/patient_management_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
    show-sql: false